server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心, 我的职责就是维护服务实例, 并不需要去检索服务
    fatch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机指向自己
      #defaultZone: http://eureka7001.com:7002/eureka/
  # 关闭自我保护机制: 默认为true
  #自我保护机制: 在网络不通畅, 或者服务宕机, 90秒内没有发送心跳, 则eureka不会立即删除服务, 则会保留一段时间
#  server:
#    enable-self-preservation: false
